#!/bin/bash

set -e

. ~/.bashrc

: ${ERLANG_VM:=kazoo_apps}

: ${ERLANG_THREADS:=25}

# options: debug info notice warning error critical alert emergency
: ${KAZOO_LOG_LEVEL:=info}
: ${KAZOO_LOG_COLOR:=true}

# options: error progress all
: ${KAZOO_SASL_ERRLOG_TYPE:=error}
: ${KAZOO_SASL_ERROR_LOGGER:=tty}

: ${DATACENTER:=dev}
: ${REGION:=local}
: ${KAZOO_ZONE:=${REGION}-${DATACENTER}}

: ${BIGCOUCH_HOST:=bigcouchbal}
: ${BIGCOUCH_DATA_PORT:=5984}
: ${BIGCOUCH_ADMIN_PORT:=5986}
: ${BIGCOUCH_COMPACT_AUTOMATICALLY:=true}

: ${KAZOO_AMQP_HOST:=rabbitmq-alpha}
: ${KAZOO_SECONDARY_AMQP_HOST:=rabbitmq-beta}


if [ "$KUBERNETES_HOSTNAME_FIX" == true ]; then
    echo "Applying kubernetes hostname fix ..."

    if [ -z "$(cat /etc/hosts | grep $HOSTNAME)" ]; then
        echo "127.0.0.1    $(hostname -f)    $(hostname)" >> /etc/hosts
        echo "::1    $(hostname -f)    $(hostname)" >> /etc/hosts
        echo "$(hostname -i | head -n 1)    $(hostname -f)    $(hostname)" >> /etc/hosts
    fi

    echo "$HOSTNAME" > /etc/hostname

    echo -e "
    HOSTNAME: $HOSTNAME
    which: $(which hostname)
    Container IP: $(hostname -i)
    Container Host: $(hostname)
    Container FQDN: $(hostname -f)
    "
fi


echo "Reading erlang cookie ..."
if [ -f '/etc/secrets/erlang/cookie' ]; then
    echo "Cookie secret mounted ..."
    ERLANG_COOKIE=$(cat /etc/secrets/erlang/cookie)
else
    echo "*** No Erlang Cookie Mounted! ***"
    ERLANG_COOKIE=insecure-cookie
fi
echo "$ERLANG_COOKIE" > ~/.erlang.cookie


echo "Creating erl_pipes ..."
mkdir -p /tmp/erl_pipes/$ERLANG_VM /var/run/kazoo


echo "Removing file based loggers since we're in docker ..."
tee /etc/kazoo/core/sys.config <<EOF
[
 {lager, [
          {handlers, [
                      {lager_console_backend, info}
                     ]},
          {colored, ${KAZOO_LOG_COLOR}}
         ,{colors, [
             {debug,     "\e[0;38m" }
            ,{info,      "\e[1;32m" }
            ,{notice,    "\e[1;36m" }
            ,{warning,   "\e[1;33m" }
            ,{error,     "\e[1;31m" }
            ,{critical,  "\e[1;35m" }
            ,{alert,     "\e[1;44m" }
            ,{emergency, "\e[1;41m" }
         ]}
         ,{error_logger_hwm, 500}
         ]}
].
EOF


echo "Configuring vm.args ..."
tee /etc/kazoo/core/vm.args <<EOF
# Tell SASL not to log progress reports, and log SASL errors to a file
-sasl errlog_type $KAZOO_SASL_ERRLOG_TYPE
-sasl sasl_error_logger $KAZOO_SASL_ERROR_LOGGER
-boot start_sasl

# Use the following erlang long hostname
-name ${ERLANG_VM}@$(env hostname -f)

# Use the following sys.config
-config /etc/kazoo/core/sys.config

# Set erlang distribution to use 11500-11999 ports instead of random
# predictibility has value here
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A $ERLANG_THREADS

# Comment this line out if you want the Erlang shell
+Bd

# Treat error_logger:warning_msg/2 as warnings instead of errors (default)
+W w

# No shell plox
-noshell

# Erlang VM to boot
-s ${ERLANG_VM}_app
EOF


# kazoo_config seems to be rejecting zone sections and also
# rejecting any section with a zone key.
#
# [zone]
# name = "$KAZOO_ZONE"
# amqp_uri = "amqp://guest:guest@$KAZOO_AMQP_HOST:5672"
# amqp_uri = "amqp://guest:guest@$KAZOO_SECONDARY_AMQP_HOST:5672"

echo "Writing kazoo config.ini ..."
tee  /etc/kazoo/core/config.ini <<EOF
[amqp]
uri = "amqp://guest:guest@$KAZOO_AMQP_HOST:5672"
uri = "amqp://guest:guest@$KAZOO_SECONDARY_AMQP_HOST:5672"

[bigcouch]
;zone = $KAZOO_ZONE
ip = "$BIGCOUCH_HOST"
port = $BIGCOUCH_DATA_PORT
admin_port = $BIGCOUCH_ADMIN_PORT
cookie = $ERLANG_COOKIE
compact_automatically = $BIGCOUCH_COMPACT_AUTOMATICALLY

[kazoo_apps]
cookie = $ERLANG_COOKIE
;zone = $KAZOO_ZONE

[ecallmgr]
cookie = $ERLANG_COOKIE
;zone = $KAZOO_ZONE

[log]
console = ${KAZOO_LOG_LEVEL,,}
EOF


echo "Ensuring permissions ..."
chown -R kazoo:kazoo ~ /etc/kazoo /tmp/erl_pipes /var/run/kazoo
chmod 0600 ~/.erlang.cookie


echo "Starting $ERLANG_VM using node: $ERLANG_VM@$(env hostname -f)"
export ERL_CRASH_DUMP=$(date +%s)_${ERLANG_VM}_erl_crash.dump
export ERL_LIBS=${HOME}/deps:${HOME}/core:${HOME}/applications:$ERL_LIBS

cd ~ 
    exec gosu kazoo erl -args_file /etc/kazoo/core/vm.args 2>&1
