#!/bin/bash -l

set -e

app=kazoo
user=$app

if [ -f /etc/default/$app ]
then
    . /etc/default/$app
fi

# This is the list of whapps that you want to autostart in this vm.
: ${KAZOO_APPS:=blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,fax,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,teletype,trunkstore,webhooks}

: ${KAZOO_RELEASE:=$(cat ~/releases/RELEASES | head -1 | cut -d',' -f3 | xargs)}
: ${ERTS_VERSION:=$(cat ~/releases/RELEASES | head -1 | cut -d',' -f4 | xargs)}

: ${ERLANG_VM:=kazoo_apps}
: ${ERLANG_THREADS:=64}
: ${ERLANG_COOKIE:=insecure-cookie}

# options: debug info notice warning error
#          critical alert emergency
: ${KAZOO_LOG_LEVEL:=info}
: ${KAZOO_LOG_COLOR:=true}

# options: error progress all
: ${KAZOO_SASL_ERRLOG_TYPE:=error}
: ${KAZOO_SASL_ERROR_LOGGER:=tty}

: ${REGION:=local}
: ${DATACENTER:=dev}

# kazoo only works when zone is set to local
# trying to figure out why only the local zone works
KAZOO_ZONE=local

: ${KAZOO_ZONE:=${REGION}-${DATACENTER}}

: ${COUCHDB_HOST:=couchdb-bal}
: ${COUCHDB_DATA_PORT:=5984}
: ${COUCHDB_ADMIN_PORT:=5986}
: ${COUCHDB_COMPACT_AUTOMATICALLY:=true}
: ${COUCHDB_USER:=admin}
: ${COUCHDB_PASS:=secret}

: ${RABBITMQ_USER:=guest}
: ${RABBITMQ_PASS:=guest}
: ${RABBITMQ_HOST_A:=rabbitmq-alpha}
: ${RABBITMQ_HOST_B:=rabbitmq-beta}

function log 
{
    local msg="$1"
    echo -e "\E[36m[*]\E[0m ${msg}" 
}


if [[ $KUBERNETES_HOSTNAME_FIX = true ]]
then
    eval $(fix-kube-hostname enable)
fi


log "Writing erlang cookie ..."
write-erlang-cookie


# note: don't worry about log level here, it's overwritten
# by the value in config.ini later
log "Writing $app sys.config ..."
tee /etc/kazoo/core/sys.config <<EOF
[
    {lager, [
        {handlers, [
            {lager_console_backend, info}
        ]},
    {colored, ${KAZOO_LOG_COLOR}},
    {colors, [
        {debug,     "\e[0;38m" },
        {info,      "\e[1;32m" },
        {notice,    "\e[1;36m" },
        {warning,   "\e[1;33m" },
        {error,     "\e[1;31m" },
        {critical,  "\e[1;35m" },
        {alert,     "\e[1;44m" },
        {emergency, "\e[1;41m" }
    ]},
    {error_logger_hwm, 500}
    ]}
].
EOF


log "Writing $app vm.args ..."
tee /etc/kazoo/core/vm.args <<EOF
# Tell SASL not to log progress reports, and log SASL errors to a file
-sasl errlog_type $KAZOO_SASL_ERRLOG_TYPE
-sasl sasl_error_logger $KAZOO_SASL_ERROR_LOGGER

# Boot kazoo $KAZOO_RELEASE release
-boot $HOME/releases/$KAZOO_RELEASE/kazoo

# Loading mode
-mode interactive

# Use the following erlang long hostname
-name $ERLANG_VM@$(env hostname -f)

# Use the following sys.config
-config /etc/kazoo/core/sys.config

# Set erlang distribution to use 11500-11999 ports instead of random
# predictibility has value here
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A $ERLANG_THREADS

# Comment this line out if you want the Erlang shell
+Bd

# Treat error_logger:warning_msg/2 as warnings instead of errors (default)
+W w

# No input
-noinput

# Enable SMP
-smp enable

# Erlang VM to boot
-s ${ERLANG_VM}_app
EOF


# Ignore this for now
# ;[zone]
# ;name = local
# ;amqp_uri = "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_HOST_A:5672"

# ;[amqp]
# ;zone = local
# ;uri = "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_HOST_A:5672"


log "Writing $app config.ini ..."
tee  /etc/kazoo/core/config.ini <<EOF
[zone]
name = $KAZOO_ZONE
amqp_uri = "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_HOST_A:5672"
amqp_uri = "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_HOST_B:5672"

[bigcouch]
ip = "$COUCHDB_HOST"
username = "$COUCHDB_USER"
password = "$COUCHDB_PASS"
port = $COUCHDB_DATA_PORT
admin_port = $COUCHDB_ADMIN_PORT
cookie = $ERLANG_COOKIE
compact_automatically = $COUCHDB_COMPACT_AUTOMATICALLY

[kazoo_apps]
host = $(env hostname -f)
cookie = $ERLANG_COOKIE
zone = $KAZOO_ZONE

[log]
console = $KAZOO_LOG_LEVEL
EOF


log "Ensuring permissions ..."
chown -R $user:$user ~ /etc/kazoo


log "Starting $ERLANG_VM@$(env hostname -f) ..."
export ERL_CRASH_DUMP=$(date +%s)_${ERLANG_VM}_erl_crash.dump
export LD_LIBRARY_PATH=$HOME/erts-$ERTS_VERSION/lib:$LD_LIBRARY_PATH
export ERTS_LIB_DIR=$HOME/lib
export KAZOO_APPS

cd ~ 
    exec gosu $user erl -args_file /etc/kazoo/core/vm.args -- foreground 2>&1
