#!/usr/bin/env bash

base=$(dirname $0)
image=telephoneorg/testdocker


if [[ $1 == 'local' ]]; then
    echo "Running tests locally ..."
    python3 $base/tests.py
else
    docker pull $image
    docker run -it --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
    	-v $(pwd):/repos/app \
        $image \
        python3 tests/tests.py
fi
