apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kazoo
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kazoo
        project: telephoneorg
        environment: production
    spec:
      initContainers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - rabbitmq
        - couchdb
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: config
        image: telephoneorg/tmpld
        imagePullPolicy: IfNotPresent
        args:
        - tmpld /templates/*.j2
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ERLANG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.hostname
        - name: KUBE_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kube.hostname.fix
        volumeMounts:
        - name: templates
          mountPath: /templates
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: 3
            memory: 3Gi
          limits:
            cpu: 3
            memory: 3Gi
      - name: dl-assets
        image: telephoneorg/kzutil:latest
        imagePullPolicy: Always
        args:
        - dl-assets
        - kazoo-sounds
        - monster-apps-core
        - monster-apps-custom
        env:
        - name: KAZOO_SOUNDS_TAG
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kzutil.kazoo.sounds.tag
        - name: MONSTER_APPS_CORE_TAG
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kzutil.monster-apps.core.tag
        - name: MONSTER_APPS_CUSTOM_TAG
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kzutil.monster-apps.custom.tag
        - name: GITHUB_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
        volumeMounts:
        - name: sounds
          mountPath: /opt/kazoo/media/prompts
        - name: monster-ui
          mountPath: /var/www/html/monster-ui
      containers:
      - name: kazoo
        image: telephoneorg/kazoo:latest
        imagePullPolicy: Always
        env:
        - name: ERLANG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.hostname
        - name: KUBE_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kube.hostname.fix
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang
              key: cookie
        - name: KAZOO_APPS
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.apps
        ports:
        - name: crossbar
          containerPort: 8000
        - name: ws-tcp
          containerPort: 5555
        - name: ws-udp
          protocol: UDP
          containerPort: 5555
        - name: fax-smtp
          containerPort: 19025
        - name: media-proxy
          containerPort: 24517
        volumeMounts:
        - name: config
          mountPath: /config
        - name: sounds
          mountPath: /opt/kazoo/media/prompts
        - name: monster-ui
          mountPath: /var/www/html/monster-ui
        resources:
          requests:
            cpu: 3
            memory: 3Gi
          limits:
            cpu: 3
            memory: 3Gi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 1200
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        securityContext:
          capabilities:
            add:
            - SYS_NICE
            - SYS_RESOURCE
      volumes:
      - name: templates
        configMap:
          name: kazoo-templates
      - name: config
        emptyDir: {}
      - name: sounds
        emptyDir: {}
      - name: monster-ui
        emptyDir: {}
      restartPolicy: Always
