#!/bin/bash -l

set -e

[[ -f /etc/entrypoint ]] && . /etc/entrypoint
[[ -f /etc/default/$APP ]] && . /etc/default/$APP

: readonly ${PUBLIC_FQDN:=$(hostname -f)}

: readonly ${COUNTRY:=us}
: readonly ${REGION:=local}
: readonly ${KAZOO_ZONE:=${COUNTRY}-${REGION}}

# This is the list of whapps that you want to autostart in this vm.
: readonly ${KAZOO_APPS:=blackhole,callflow,cdr,conference,crossbar,doodle,ecallmgr,hangups,hotornot,konami,jonny5,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,teletype,trunkstore,webhooks}
: readonly ${ERLANG_COOKIE:=insecure-cookie}

: declare -ir ${ERLANG_PROCESSES:=$(( $(nproc) * 2048 ))}
: declare -ir ${ERLANG_THREADS:=$(( $(nproc) * 32 ))}

# options: debug info notice warning error critical alert emergency
: readonly ${KAZOO_LOG_LEVEL:=info}
: readonly ${KAZOO_LOG_COLOR:=true}


: readonly ${COUCHDB_HOST:=couchdb}
: readonly ${COUCHDB_DATA_PORT:=5984}
: readonly ${COUCHDB_ADMIN_PORT:=5986}
# : readonly ${COUCHDB_COMPACT_AUTOMATICALLY:=true}
: readonly ${COUCHDB_USER:=}
: readonly ${COUCHDB_PASS:=}

: readonly ${RABBITMQ_HOST:=rabbitmq}

: readonly ${RABBITMQ_USER:=guest}
: readonly ${RABBITMQ_PASS:=guest}


for file in sys.config vm.args config.ini; do
    if [[ -e /config/$file ]]; then
        ln -sf /config/$file /etc/kazoo/core/$file
    fi
done


if [[ ! -e /config/sys.config ]]; then
    log::m-info "Writing $APP sys.config ..."
    tee /etc/kazoo/core/sys.config <<EOF
[
    {lager, [
        {handlers, [
            {lager_console_backend, info}
        ]},
    {colored, ${KAZOO_LOG_COLOR}},
    {colors, [
        {debug,     "\e[0;38m" },
        {info,      "\e[1;32m" },
        {notice,    "\e[1;36m" },
        {warning,   "\e[1;33m" },
        {error,     "\e[1;31m" },
        {critical,  "\e[1;35m" },
        {alert,     "\e[1;44m" },
        {emergency, "\e[1;41m" }
    ]},
    {error_logger_hwm, 500}
    ]}
].
EOF
fi


if [[ ! -e /config/vm.args ]]; then
    log::m-info "Writing $APP vm.args ..."
    tee /etc/kazoo/core/vm.args <<EOF
# disable sasl error logger
-sasl sasl_error_logger false

# Boot kazoo $KAZOO_RELEASE release
-boot /opt/kazoo/releases/4.0.0/kazoo

# Loading mode
-mode interactive

# Use the following erlang long hostname
-name kazoo_apps

# Use the following sys.config
-config /etc/kazoo/core/sys.config

# Set erlang distribution to use 11500-11999 ports instead of random
# predictibility has value here
-kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A $ERLANG_THREADS

# Maximum number of processes
+P $ERLANG_PROCESSES

# Comment this line out if you want the Erlang shell
+Bd -noinput

# Treat error_logger:warning_msg/2 as warnings instead of errors (default)
+W w

# Erlang VM to boot
-s kazoo_apps_app
EOF
fi


if [[ ! -e /config/config.ini ]]; then
    log::m-info "Writing $APP config.ini ..."
    cat > /etc/kazoo/core/config.ini <<EOF
[zone]
name = $KAZOO_ZONE
amqp_uri = "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_HOST:5672"

[bigcouch]
ip = "$COUCHDB_HOST"
port = $COUCHDB_DATA_PORT
admin_port = $COUCHDB_ADMIN_PORT
cookie = $ERLANG_COOKIE
compact_automatically = true
;;;username = "$COUCHDB_USER"
;;;password = "$COUCHDB_PASS"

[kazoo_apps]
host = $PUBLIC_FQDN
cookie = $ERLANG_COOKIE
zone = $KAZOO_ZONE

[log]
console = $KAZOO_LOG_LEVEL
EOF
# if COUCHDB_USER + COUCHDB_PASS non-empty unescape the username and password
# above.
if [[ ! -z $COUCHDB_USER && ! -z $COUCHDB_PASS ]]; then
    sed -i 's/^\;\;\;//g' /etc/kazoo/core/config.ini
fi
cat /etc/kazoo/core/config.ini
fi


log::m-info "Ensuring permissions ..."
fixattrs


log::m-info "Starting $APP ..."
cd ~
    exec gosu $USER erl -args_file /etc/kazoo/core/vm.args -- foreground 2>&1
