#!/usr/bin/env bash

: ${NAME:=kazoo}
: ${ACCOUNT:=test}
: ${REALM:=localhost}
: ${ADMIN_USER:=admin}
: ${ADMIN_PASS:=secret}

: ${LANGUAGE:=en-us}
: ${MEDIA_PATH:=/opt/kazoo/media/prompts/en/us}
: ${KAPPS_PATH:=/var/www/html/monster-ui/apps}
: ${CROSSBAR_URI:=http://localhost:8000/v2}
: ${FREESWITCH_HOST:=freeswitch.local}
: ${KAMAILIO_HOST:=kamailio.valuphone.local}

function create-master-acccount {
	docker exec $NAME sup crossbar_maintenance create_account $ACCOUNT $REALM $ADMIN_USER $ADMIN_PASS
}

function load-media {
	docker exec $NAME sup kazoo_media_maintenance import_prompts $MEDIA_PATH $LANGUAGE
}

function init-apps {
	docker exec $NAME sup crossbar_maintenance init_apps $KAPPS_PATH $CROSSBAR_URI
}

function add-fs-node {
	docker exec $NAME sup ecallmgr_maintenance add_fs_node freeswitch@$FREESWITCH_HOST
}

function allow-sbc {
	local kamailio_ip=$(docker exec -ti kamailio hostname -i)
	docker exec $NAME sup ecallmgr_maintenance allow_sbc $KAMAILIO_HOST $kamailio_ip
}

function get-master-account {
	docker exec $NAME sup crossbar_maintenance find_account_by_name $ACCOUNT
}

function sup {
	docker exec $NAME sup "$@"
}


if [[ $1 ]]; then
    "$@"
else
    echo "usage: $(basename $0) {create-master-acccount|load-media|init-apps|add-fs-node|allow-sbc|get-master-account}"
    exit 1
fi
