#!/usr/bin/env bash

: ${HOST:=minikube.valuphone.local}
: ${POD:=$(kubectl get po -l app=kazoo --no-headers | awk '{print $1}')}

: ${FREESWITCH_HOST:=$HOST}
: ${KAMAILIO_HOST:=$HOST}
: ${KAMAILIO_IP:=$(minikube ip)}

function sup {
	kubectl exec $POD -- sup "$@"
}

source $(dirname $0)/assets/do-common.inc
