#!/usr/bin/env bash

: ${HOST:=localhost}
: ${CONTAINER:=kazoo}

: ${FREESWITCH_HOST:=freeswitch.local}
: ${KAMAILIO_HOST:=kamailio.valuphone.local}
: ${KAMAILIO_IP:=$(docker exec -ti kamailio hostname -i)}

function sup {
	docker exec $CONTAINER sup "$@"
}

source $(dirname $0)/assets/do-common.inc
