#!/bin/bash -l

set -e

log::m-info "Kazoo Sounds: $KAZOO_SOUNDS_VERSION"
tmpd=$(mktemp -d)
pushd $tmpd
    log::m-info "  Downloading ..."
    curl -LO https://github.com/telephoneorg/kazoo-builder/releases/download/v$KAZOO_VERSION/kazoo-sounds_$KAZOO_SOUNDS_VERSION.deb
    log::m-info "  Installing ...\n"
    dpkg -i kazoo-sounds_*.deb
    popd && rm -rf $tmpd


log::m-info "Monster Apps: $MONSTER_APPS_TAG "
tmpd=$(mktemp -d)
pushd $tmpd
    log::m-info "  Downloading ..."
    curl -LO https://github.com/telephoneorg/monster-ui-builder/releases/download/v$MONSTER_APPS_TAG/monster-ui-debs-all.tar.gz
    log::m-info "  Installing ...\n"
    tar xzvf monster-ui-*.tar.gz
    dpkg -i monster*.deb
    popd && rm -rf $tmpd
